### PR TITLE
More oo-like implementation, single toggle-command, better cursor-placement

### PR DESCRIPTION
**Pull request by alphaone**
Hi Hiroki,

after I couldn't really figure out, how the cursor is placed in your implementation, I started to refactor your code into more manageable junks, methods and even classes.

At the end I had a RubyBlockConverter that:
- could toggle blocks between curly and do-end
- replaced as little of the document as possible, to prevent cursor form moving
- should be better readable (and hopefully more understandable) to new contributors

I'm not sure, that all the features of the current implementation still work, since I was not able to implement automatic tests with the given ruby examples. How do you test your plugins?

Best regards,
Torsten

### CODE REVIEW

**Comment by irohiroki** [comment]
what a big rewriting! but your concept sounds great. allow me to take some time to review your PR, please?

btw, automatic tests are my dream. I've not got there.

**Comment by alphaone** [comment]
Please, take your time!

I am really sorry, that i missed commiting single steps on my way during the refactoring. That would have made it easier for you to follow my intention. But when I was starting the refactoring, I did not thought about contributing, I just wanted to understand, what the plugin does.

**Comment by irohiroki** [comment]
I've read most of your code. It's really oo, and I got a couple of python techniques same time. thanks!
but unfortunately it doesn't really behave the same with the original version.
could you tell me again when you manage to make it.
good luck!

**Comment by taasaa** [comment]
Any chance this PR will be merged into master? Or is this plugin development died?

**Comment by irohiroki** [comment]
@taasaa I'd be happy to merge this PR if this branch behaves same as the master.

**Comment by irohiroki** [comment]
I mean, if this branch is capable as the original, other than key mappings. that can be verified with the files in the `test` directory.

**Comment by dportalesr** [comment]
Any hope of this getting merged?

**Pull request closed without merging**
