### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by dsandstrom**
added `import StringIO if`import io`fails
added`io = StringIO`

### CODE REVIEW

**Comment by dsandstrom** [comment]
Was working on `Ruby on Rails` syntax.  I tried on RSpec, but it did not, but may be a different issue.

**Comment by irohiroki** [comment]
by the way, is StringIO compatible with ST3 on linux?
I like to keep the plugin ST3 compatible when possible.

**Comment by dsandstrom** [comment]
I'm not sure, but I will try it out.

**Comment by dsandstrom** [comment]
The master branch (with io) worked just fine on my system.  Just for fun, I replaced io with StringIO and received error: `ImportError: No module named 'StringIO'`.  I noticed ST3 uses Python 3.3.  So, apparently, 3.3 uses io instead of StringIO.  Obviously, I do not know Python so I'm just guessing and checking.

**Comment by irohiroki** [comment]
Thanks for testing! so, now the plugin is ST3-ready on Mac only. it's ok until the release of ST3.

**Comment by dsandstrom** [comment]
Just to clarify, your plugin is st3 ready for linux.  When using st2, linux users can use the linux branch.

**Comment by irohiroki** [comment]
is it? that is, ST3 for linux has io module?

**Comment by dsandstrom** [comment]
Yes, I ran st3 and installed your package from the package manager and it worked fine.  StringIO does not work, however.  But it is not needed because io works.

**Comment by irohiroki** [comment]
@dsandstrom Thank you! I'll update the compatibility info!

**Pull request merged**
