### PR TITLE
place cursor inside block after conversion

### PR DESCRIPTION
**Pull request by alphaone**
fixing #1

### CODE REVIEW

**Comment by alphaone** [comment]
I just fiddled around, how I can set the cursor ... it works for me, but no guarantee that all of the usecases are covered

**Comment by irohiroki** [comment]
I think multiple cursors must be supported on ST but `view.sel().clear()` clears all, including irrelevant ones.
can you save those?

**Comment by alphaone** [comment]
I moved the view.sel().clear() in front of the loop, so that the selections, that get created in the iterations of the loop won't get cleared. works from my perspective ...

**Comment by irohiroki** [comment]
clear() should be avoided, to keep cursors **outside** of braces.
can you give a try the tip of master? I pushed a commit there.

**Comment by irohiroki** [comment]
an alternative merged.

**Pull request closed without merging**
